language: python
python:
  - "2.7"
  - "2.6"
cache:
  directories:
    - $HOME/.pip-cache/
env: SETTINGS_MODULE=testsettings
install:
  - pip install -r requirements-dev.txt --download-cache $HOME/.pip-cache
script:
  - py.test tests/ --cov betty --cov-report term-missing
after_success:
  - coveralls
notifications:
  email:
    - csinchok@theonion.com