language: python
python:
  - "2.7"
  - "2.6"
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - pip install -r requirements.txt --download-cache $HOME/.pip-cache
  - pip install coveralls
script:
  - coverage run --source=betty tests/runtests.py
after_success:
  - coveralls
notifications:
  email:
    - csinchok@theonion.com