language: python
python:
  - '2.7'
  - '3.4'
matrix:
  allow_failures:
    - python: '3.4'
cache: apt
before_install:
  # Miniconda workaround for installing scipy in Travis
  - '[ "$TRAVIS_PYTHON_VERSION" = "2.7" ] && wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh || true'
  - '[ "$TRAVIS_PYTHON_VERSION" = "3.4" ] && wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh || true'
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - '[ "$TRAVIS_PYTHON_VERSION" = "2.7" ] && export PATH=/home/travis/miniconda2/bin:$PATH || true'
  - '[ "$TRAVIS_PYTHON_VERSION" = "3.4" ] && export PATH=/home/travis/miniconda3/bin:$PATH || true'
  - conda update --yes conda
  - '[ "$TRAVIS_PYTHON_VERSION" = "2.7" ] && travis_retry conda install --yes python=2.7 pip numpy scipy || true'
  - '[ "$TRAVIS_PYTHON_VERSION" = "3.4" ] && travis_retry conda install --yes python=3.4 pip numpy scipy || true'
install:
  - travis_retry pip install -e .
  - travis_retry pip install file://$(pwd)#egg=betty-cropper[dev]
script:
  - py.test --cov betty --cov-report term-missing
  - scripts/lint
after_success:
  - coveralls
notifications:
  email:
    - csinchok@theonion.com
  on_failure: change
  on_success: change
deploy:
  provider: pypi
  user: csinchok
  password:
    secure: XZlMTIFA8E4jDIbA8m81pH1owQlGLULJ2DXFRsFrKnvmZ/SJOv4F329y2aHW65qvaz67gcNbZg259biL6eZrKG8vIOMzdrC/D3fCgRZSR59tI7WxRj0vX40Pz3E2FzN6QDI8Jbv6+M7wqgHuBDgXWDyEiGRg4arVp1La/dQEg4Y=
  on:
    tags: true
    repo: theonion/betty-cropper
    python: 2.7
