language: python
sudo: required
python:
    - '2.7'
    - '3.5'
services:
    - docker
before_install:
    # Set base Python image version (leverages Travis build matrix)
    - sed -i'' "s/^\(FROM python:\).*/\1${TRAVIS_PYTHON_VERSION}/" Dockerfile
install:
    - docker build --tag betty .
script:
    - docker run betty py.test --cov betty --cov-report term-missing
    - docker run betty flake8 .
after_success:
    - docker run betty coveralls
