language: python
python:
  - "2.7"
  - "2.6"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script:
  - coverage run --source=betty runtests.py
after_success:
  - coveralls
notifications:
  email:
    - csinchok@theonion.com