language: python
python:
- '2.7'
- '3.4'
matrix:
  allow_failures:
    - python: '3.4'
cache: apt
before_install:
  - '[ "$TRAVIS_PYTHON_VERSION" = "2.7" ] && wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh || true'
  - '[ "$TRAVIS_PYTHON_VERSION" = "3.4" ] && wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh || true'
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - travis_retry conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy
install:
  - travis_retry pip install -e .
  - travis_retry pip install file://$(pwd)#egg=betty-cropper[dev]
script:
  - py.test tests/ --cov betty --cov-report term-missing
after_success:
  - coveralls
notifications:
  email:
    - csinchok@theonion.com
  on_failure: change
  on_success: change
virtualenv:
  system_site_packages: true
deploy:
  provider: pypi
  user: csinchok
  password:
    secure: XZlMTIFA8E4jDIbA8m81pH1owQlGLULJ2DXFRsFrKnvmZ/SJOv4F329y2aHW65qvaz67gcNbZg259biL6eZrKG8vIOMzdrC/D3fCgRZSR59tI7WxRj0vX40Pz3E2FzN6QDI8Jbv6+M7wqgHuBDgXWDyEiGRg4arVp1La/dQEg4Y=
  on:
    tags: true
    repo: theonion/betty-cropper
    python: 2.7
